### ISSUE TITLE
Cache file cannot be created.

### ISSUE THREAD

**Issue by TheFrozenDuck** [digrouz/docker-ddclient#1]
Hi,
when I'm starting the container the client updates the ip-address but eventually crashes with following message:
`FATAL:    Cannot create file '/var/cache/ddclient/ddclient.cache'. (No such file or directory)`

Following this error I tried to create another volume pointing to the directory and after that to the cache file itself but each time I get an error message. 
` FATAL:    Cannot create file '/var/cache/ddclient/ddclient.cache'. (Permission denied)`

With kind regards,
Raphael

**Comment by digrouz** [comment]
Hi,

Which version are you using, the CentOS or the Alpine ?

Kind Regards

Nicolas

**Comment by TheFrozenDuck** [comment]
I'm using the latest Alpine one (3.7).

I also attached the content of my compose file:

`ddclient:`
`    image: digrouz/ddclient:alpine3.7`
`    volumes:`
`     - ./docker/ddclient/ddclient.conf:/etc/ddclient/ddclient.conf`
`     - ./docker/ddclient/ddclient.cache:/var/cache/ddclient/ddclient.cache`
`     - /etc/localtime:/etc/localtime:ro`

**Comment by TheFrozenDuck** [comment]
I might have found the problem and a workaround. With the aforementioned compose file docker successfuly takes over the provided **ddclient.cache** file. At the same time it also seems to mark it to belong to the ""root"" user and group, which eventually explains the `(Permission Denied)`. If I `chwon` it to the default ids it can be accessed and successfully be used.

I am unsure if this error is caused by the Dockerfile or rather my system configuration as I followed the official installation and post installation guides of Docker so I hope that I didn't miss anything.

**Comment by digrouz** [comment]
This is anyway an issue if the process cannot access that folder.

I just issued a fix in throught the entrypoint, could try again with the latest image ?

**Comment by digrouz** [comment]
Wait for it, dockerhub seems busy tonight :)

**Comment by digrouz** [comment]
it is build now, can you test ?

**Comment by TheFrozenDuck** [comment]
I just tested it and it works like a charm. Thanky you very much for your fast repsonse and the fast fix.

Kind regards,
Raphael
